name: Run scheduled regression test

on:
  schedule:
    - cron: '*/5 * * * *'  

jobs:
  run-regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Install NPM
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run regression tests
        run: npm run test:e2e
        env:
          USERNAME: "standard_user"
          PASSWORD: "secret_sauce"
